export const AGE_BASED_QUESTIONS = {
  en: {
    under20: [
      "How to relieve period pain quickly?",
      "What to do about period acne?",
      "Is irregular period normal?",
      "Tips for using tampons for the first time?",
      "Can I exercise during my period?",
    ],
    age20to34: [
      "Side effects of long-term birth control?",
      "How to calculate ovulation?",
      "Period late due to stress?",
      "Relief for menstrual migraines?",
      "Is IUD right for me?",
    ],
    age35to39: [
      "Preparing for pregnancy after 35?",
      "How to assess my fertility?",
      "Stress management for working moms?",
      "Is lighter flow a sign of aging?",
      "Nutrition tips for conception",
    ],
    age40to45: [
      "Is shorter cycle a sign of perimenopause?",
      "Improving sleep during period?",
      "Managing mood swings?",
      "Do I still need birth control after 40?",
      "Preventing osteoporosis early?",
    ],
    over45: [
      "Symptoms of perimenopause?",
      "Natural relief for hot flashes?",
      "Is HRT safe?",
      "Bone health after menopause?",
      "Weight management during perimenopause",
    ],
    default: [
      "How to relieve period pain?",
      "Foods to avoid during period?",
      "Improving sleep during period?",
      "How stress affects menstruation?",
      "What is a normal cycle?",
    ],
  },
  zh: {
    under20: [
      "如何快速缓解痛经？",
      "经期长痘痘怎么办？",
      "月经不规律正常吗？",
      "第一次使用卫生棉条要注意什么？",
      "经期可以运动吗？",
    ],
    age20to34: [
      "长期服用避孕药有副作用吗？",
      "如何计算排卵期？",
      "工作压力大导致经期推迟怎么办？",
      "经期偏头痛如何缓解？",
      "IUD（宫内节育器）适合我吗？",
    ],
    age35to39: [
      "35岁后备孕需要注意什么？",
      "如何评估我的生育力？",
      "职场妈妈如何管理压力？",
      "经量变少是早衰吗？",
      "备孕期间的营养补充建议",
    ],
    age40to45: [
      "经期缩短是围绝经期的征兆吗？",
      "如何改善经期睡眠质量？",
      "情绪波动大怎么调节？",
      "40岁后还需要避孕吗？",
      "预防骨质疏松现在开始晚吗？",
    ],
    over45: [
      "围绝经期有哪些典型症状？",
      "潮热盗汗如何自然缓解？",
      "激素替代疗法(HRT)安全吗？",
      "绝经后如何保持骨骼健康？",
      "围绝经期的体重管理建议",
    ],
    default: [
      "如何缓解痛经？",
      "经期饮食有哪些禁忌？",
      "如何改善经期睡眠？",
      "压力对月经有什么影响？",
      "什么是正常的月经周期？",
    ],
  },
};
